// export const USER_SIGNIN = "USER_SIGNIN"

export const USER_SIGNUP = "USER_SIGNUP"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const USER_UPDATE_SUCCES = "USER_UPDATE_SUCCES"